### PR TITLE
Fix bug in calculating BC dates for display.

### LINKED ISSUE #72: MODS indexing:  fix BC year in pub_year_display_str
Turns out there is no year 0, so for etdf dates (any years with 0), so pub_year_display_str  needs a tweak:

0 becomes 1  B.C.
-1 or 1 B.C.  becomes 2 B.C.
-999 or 999 B.C.  becomes  1000 B.C.
etc.

basically, find the tests that have year 0 or BC years expected, and change them as necessary for the formats necessary.  It's not clear to me if this is ONLY for etdf format, or for other formats as well.

### PR DESCRIPTION
**Pull request by jkeck**
Closes #72

### CODE REVIEW

File: spec/fixtures/searchworks_pub_date_data.rb [hunk 1]
```diff
@@ -782,17 +782,17 @@
       mods_origin_info_start_str +
         '<dateCreated encoding="edtf" point="start" keyDate="yes">-18</dateCreated>' +
         '<dateCreated encoding="edtf" point="end">-17</dateCreated>' +
-        mods_origin_info_end_str => [-18, '18 B.C. - 17 B.C.'],
+        mods_origin_info_end_str => [-18, '19 B.C. - 17 B.C.'],
```
Comment (ndushay) [inline spec/fixtures/searchworks_pub_date_data.rb]: actually, the second date should be changed too, for when we really do date ranges.  However, that display string is going to be via imprint_display code anyway, so if it matters, I'll get it in the coding changes I'm working on now.
